### ISSUE TITLE
Default bucket support?

### ISSUE THREAD

**Issue by Halama** [keboola/ex-teradata#11]
Would this work with current UI implementation where it expects `outputTable` in configuration?
@pivnicek

**Comment by pivnicek** [comment]
It may require a minor update, but I think we should go ahead with it anyways.  The other extractors should be updated to support default buckets also imho.

**Comment by Halama** [comment]
I've talked about this with @pivnicek and maybe it will be more complicated. So we'll start here without default bucket like other db extractors.

**Comment by pivnicek** [comment]
closing this since it will behave like other db-exes.
