### ISSUE TITLE
Empty tables support

### ISSUE THREAD

**Issue by Halama** [keboola/ex-teradata#9]
Vytvorit .csv soubor se zahlavim i v pripade, ze databaze nevrati zadne radky
 Najit zpusob jak dostat sloupce potencialniho vysledku SQL, krome parsovani dotazu

**Comment by Actimel** [comment]
Vyreseno https://github.com/keboola/ex-teradata/pull/1/commits/3c6746d8c68a306f9e705b5fda8c93d51e9347ed
